# Site settings
title: My GSoC contributor journey
description: All of the updates on my GSoC learning progress
url: https://irenebernardi.github.io     # Update this with your GitHub Pages URL
baseurl: ""                             # Leave this empty for GitHub Pages

# Theme settings
theme: minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
  
                                      # You can explore other themes at https://jekyllthemes.io/

# Markdown settings
markdown: kramdown                     # Use kramdown as the default Markdown engine

# Exclude files/folders from the build (optional)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

# GitHub Pages settings
github_pages:
  jekyll_version: 3.9.0                # Set the version of Jekyll you want to use
            


plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
